services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      - traefik.http.routers.sbs-n8n-https.rule=Host(`${APPS_N8N_DOMAIN}`)
      - traefik.http.routers.sbs-n8n-https.entrypoints=websecure
      - traefik.http.routers.sbs-n8n-https.tls.certresolver=letsencrypt
      - traefik.http.routers.sbs-n8n-https.service=sbs-n8n
      - traefik.http.routers.sbs-n8n-http.rule=Host(`${APPS_N8N_DOMAIN}`) && !PathPrefix(`/.well-known/acme-challenge`)
      - traefik.http.routers.sbs-n8n-http.entrypoints=web
      - traefik.http.routers.sbs-n8n-http.middlewares=sbs-n8n-redirect-to-https
      - traefik.http.routers.sbs-n8n-http.service=sbs-n8n
      - traefik.http.middlewares.sbs-n8n-redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.sbs-n8n-redirect-to-https.redirectscheme.permanent=true
      - traefik.http.services.sbs-n8n.loadbalancer.server.port=5678
    environment:
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_HOST: ${APPS_N8N_DOMAIN}
      N8N_PROTOCOL: https
      N8N_SECURE_COOKIE: "true"
      WEBHOOK_URL: https://${APPS_N8N_DOMAIN}/
      NODE_ENV: production
      GENERIC_TIMEZONE: ${APPS_N8N_TIMEZONE}
      TZ: ${APPS_N8N_TIMEZONE}
      APPS_N8N_DOMAIN: ${APPS_N8N_DOMAIN}
      APPS_N8N_TIMEZONE: ${APPS_N8N_TIMEZONE}
    volumes:
      - ../data/apps/n8n:/home/node/.n8n

  ai-consult-web:
    build: ../apps/static/ai-consult-11ty
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      - traefik.http.routers.ai-consult-11ty-https.rule=Host(`${APPS_STATIC_AI_CONSULT_DOMAIN}`)
      - traefik.http.routers.ai-consult-11ty-https.entrypoints=websecure
      - traefik.http.routers.ai-consult-11ty-https.tls.certresolver=letsencrypt
      - traefik.http.routers.ai-consult-11ty-https.service=ai-consult-11ty
      - traefik.http.routers.ai-consult-11ty-http.rule=Host(`${APPS_STATIC_AI_CONSULT_DOMAIN}`) && !PathPrefix(`/.well-known/acme-challenge`)
      - traefik.http.routers.ai-consult-11ty-http.entrypoints=web
      - traefik.http.routers.ai-consult-11ty-http.middlewares=ai-consult-11ty-redirect-to-https
      - traefik.http.routers.ai-consult-11ty-http.service=ai-consult-11ty
      - traefik.http.middlewares.ai-consult-11ty-redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.ai-consult-11ty-redirect-to-https.redirectscheme.permanent=true
      - traefik.http.services.ai-consult-11ty.loadbalancer.server.port=80
    environment:
      APPS_STATIC_AI_CONSULT_DOMAIN: ${APPS_STATIC_AI_CONSULT_DOMAIN}

  whyeven-web:
    build: ../apps/static/whyeven-11ty
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      - traefik.http.routers.whyeven-11ty-https.rule=Host(`${APPS_STATIC_WHYEVEN_DOMAIN}`)
      - traefik.http.routers.whyeven-11ty-https.entrypoints=websecure
      - traefik.http.routers.whyeven-11ty-https.tls.certresolver=letsencrypt
      - traefik.http.routers.whyeven-11ty-https.service=whyeven-11ty
      - traefik.http.routers.whyeven-11ty-http.rule=Host(`${APPS_STATIC_WHYEVEN_DOMAIN}`) && !PathPrefix(`/.well-known/acme-challenge`)
      - traefik.http.routers.whyeven-11ty-http.entrypoints=web
      - traefik.http.routers.whyeven-11ty-http.middlewares=whyeven-11ty-redirect-to-https
      - traefik.http.routers.whyeven-11ty-http.service=whyeven-11ty
      - traefik.http.middlewares.whyeven-11ty-redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.whyeven-11ty-redirect-to-https.redirectscheme.permanent=true
      - traefik.http.services.whyeven-11ty.loadbalancer.server.port=80
    environment:
      APPS_STATIC_WHYEVEN_DOMAIN: ${APPS_STATIC_WHYEVEN_DOMAIN}
